# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.URLField(blank=True, default='', help_text='image link')),
                ('level', models.CharField(choices=[('Hard', 'Hard'), ('Normal', 'Normal')], default='Normal', max_length=20)),
            ],
        ),
    ]
