# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(help_text='Numeric, Eg: 50000')),
                ('quantity', models.IntegerField(help_text='Numeric, Eg: 35')),
                ('product_type', models.CharField(blank=True, choices=[('tv', 'TV'), ('refrigerator', 'Refrigerator'), ('ac', 'AC'), ('washing_machine', 'Washing Machine')], default='tv', max_length=20, null=True)),
                ('cover', models.URLField(blank=True, default='', help_text='image link for cover (1300x500)')),
            ],
        ),
    ]
