# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.URLField(blank=True, default='', help_text='image link for cover'),
        ),
    ]
