# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.URLField(default='', help_text='image link'),
        ),
    ]
