# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170408_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(null=True, upload_to='facemash_photos'),
        ),
    ]
